### ISSUE TITLE
Hand models need animations

### ISSUE THREAD

**Issue by patrykkalinowski** [patrykkalinowski/godot-xr-kit#4]
For OpenXR runtimes other than SteamVR, if player uses controller, hand skeleton data is not provided and current implementation of physical hands breaks.

Without skeleton data, hand model should follow controllers (XRController3D node) and play animations based on received button clicks (ex. grip).

I have uploaded hand animation files extracted from SteamVR [here](https://github.com/patrykkalinowski/godot-xr-kit/tree/master/addons/xr-kit/physical-movement/assets/valve_hand_models/animations). These need to be properly transformed for hand models used by physical-movement module, but I don't have 3d/animation skills to do it.

**Comment by DigitalN8m4r3** [comment]
Using the valve hands and its animations doesnt make sense, adding on this,
the Hand models i made for the xr tools kit, are made with OpenXR standard, bone naming etc. in mind and they come with a highpoly and lowpoly variant along with 3 different types.

It was a lengthy process that involved many Updates.

They come with a dozen of premade animations and in theory they should work out of the box with your xr kit.
when i get time, will test my theory and report Back, anyways it should be almost a drag n drop

**Comment by patrykkalinowski** [comment]
Thanks @DigitalN8m4r3. Adding your hands is next on my roadmap. I believe multiple working models are beneficial, that's why I want to keep valve hands and make them work fully.

**Comment by DigitalN8m4r3** [comment]
hmm, i do understand your motivation... anyways glad that you are considering the xr tools hand models.

Thanks

**Comment by patrykkalinowski** [comment]
Unfortunately, @DigitalN8m4r3 's hand models were unsuitable for hand tracking (bone rotations incompatible with OpenXR), so I had to adapt valve hands animations for that. Anyways, hand models are now animated and plugin works with controllers, too.
