### ISSUE TITLE
Adding interactables

### ISSUE THREAD

**Issue by lyniakk** [patrykkalinowski/godot-xr-kit#8]
Hello, 
do you plan to add some interactable buttons, joysticks, handles,... into xr kit?
Since the ones included in xr tools do not work with hand tracking, I think it would be great addition.

**Comment by patrykkalinowski** [comment]
Yes, I have them planned, but no timeline. I suppose it will take at least few months before I start working on physical interactables.

**Comment by patrykkalinowski** [comment]
Basic interactables are available in playground scene on `new-playground` branch
